services:
  - type: web
    name: 10vote-ws-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: WS_PORT
        value: 8080
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: SELF_SCOPE
        value: 10vote
      - key: SELF_ENDPOINT
        value: https://playground.self.xyz/api/verify


